out_dir: results/PROTEINS
dataset:
  format: PyG
  name: TU_PROTEINS
  task: link_pred
  task_type: classification
  transductive: True
  #split: [0.8, 0.2]
  augment_feature: [node_MMPCA] # node_EDEN, node_PCA, node_MMPCA, node_RMMPCA 
  augment_feature_dims: [3]
  augment_feature_repr: position
  augment_label: ''
  augment_label_dims: 5
  transform: none
  edge_train_mode: disjoint
train:
  batch_size: 32
  eval_period: 20
  ckpt_period: 100
model:
  type: gnn
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: add
gnn:
  layers_pre_mp: 0
  layers_mp: 5
  layers_post_mp: 1
  dim_inner: 32
  layer_type: gcnconv
  stage_type: stack
  batchnorm: False
  act: relu
  dropout: 0.0
  agg: add
  normalize_adj: False
optim:
  optimizer: adam
  base_lr: 0.01
  max_epoch: 100