# The recommended basic settings for GNN
out_dir: results/CiteSeer
dataset:
  format: PyG
  name: CiteSeer
  # Whether to use an encoder for general attribute features
  encoder: False
  encoder_bn: False
  task: node
  task_type: classification
  transductive: True
  #split: [0.8, 0.2 ]
  augment_feature: [node_RNI] # node_EDEN, node_PCA, node_MMPCA, node_RMMPCA, RNI
  augment_feature_dims: [8]
  augment_feature_repr: original
  augment_label: ''
  augment_label_dims: 0
  transform: none
train:
  batch_size: 128
  eval_period: 10
  ckpt_period: 1000
model:
  type: gnn
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: add
gnn:
  layers_pre_mp: 1
  layers_mp: 3
  layers_post_mp: 1
  dim_inner: 32
  layer_type: ginconv
  stage_type: stack
  batchnorm: False
  act: relu
  dropout: 0.0
  agg: add
  normalize_adj: False
optim:
  optimizer: adam
  base_lr: 0.01
  max_epoch: 100